esphome:
    name_add_mac_suffix: false
  
# Enable logging
logger:

web_server:
    port: 80
    include_internal: true
    auth: 
        username: !secret basic_auth_user
        password: !secret basic_auth_password

ota:
    safe_mode: true
    password: !secret ota_password
    id: ota

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    # No SSID Specified to use the device name
    password: !secret fallback_ap_password

captive_portal:

button:
  - platform: restart
    name: "Restart (Normal Mode)"
    internal: true
  - platform: safe_mode
    name: "Restart (Safe Mode)"
    internal: true

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 600s
    entity_category: "diagnostic"
  - platform: uptime
    name: Uptime
    update_interval: 600s
    entity_category: "diagnostic"
