esphome:
    name: ${device_name}
    name_add_mac_suffix: false
  
# Enable logging
logger:

web_server:
    port: 80
    include_internal: true
    auth: 
        username: ${web_server_username}
        password: ${web_server_password}

# Enable Home Assistant API
api:
    encryption:
        key: ${api_encryption_key}

ota:
    safe_mode: true
    password: ${ota_password}

wifi:
    ssid: ${wifi_ssid}
    password: ${wifi_password}
    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "${device_name} Fallback Hotspot"
        password: ${access_point_password}

captive_portal: