api:
  id: main_api
  on_client_connected:
    then:
      - script.execute: update_connection_status
  on_client_disconnected: 
    then:
      - script.execute: update_connection_status

### Sensors

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Europe/Paris"
    on_time:
      - minutes: '*'
        seconds: 0
        then:
           - lvgl.label.update:
              id: time_label
              text:
                time_format: "%R"
                time: homeassistant_time
           - lambda: |-
              char date_buf[30];
              time_t now = id(homeassistant_time).now().timestamp;
              struct tm* timeinfo = localtime(&now);
              
              // Tableaux de traduction
              const char* jours[] = {"Dimanche", "Lundi", "Mardi", "Mercredi", 
                                     "Jeudi", "Vendredi", "Samedi"};
              const char* mois[] = {"janvier", "février", "mars", "avril", "mai", "juin",
                                    "juillet", "août", "septembre", "octobre", "novembre", "décembre"};
              
              // Format: Jour DD Mois Année
              snprintf(date_buf, sizeof(date_buf), "%s %02d %s %04d", 
                jours[timeinfo->tm_wday],
                timeinfo->tm_mday,
                mois[timeinfo->tm_mon],
                timeinfo->tm_year + 1900
              );

              lv_label_set_text(id(date_label), date_buf);


light:
  - id: !extend ${light}
    on_turn_on: 
      then: 
        - lvgl.widget.update: 
            id: [light_btn, light_icon]
            state: 
              checked: true
        - lvgl.widget.show: [light_state_on, light_status_text_on]
        - lvgl.widget.hide: [light_state_off, light_status_text_off]
    on_turn_off: 
      then: 
        - lvgl.widget.update: 
            id: [light_btn, light_icon]
            state: 
              checked: false
        - lvgl.widget.show: [light_state_off, light_status_text_off]
        - lvgl.widget.hide: [light_state_on, light_status_text_on]

sensor:
  - platform: homeassistant
    entity_id: ${room_temperature_entity_id}
    id: temperature
    on_value:
      - lvgl.label.update:
          id: temp_value
          text:
            format: "%.1f°"
            args: [ 'x' ]  

  - platform: homeassistant
    id: room_humidity
    entity_id: ${room_humidity_entity_id}
    on_value:
      - lvgl.label.update:
          id: humidity_value
          text:
            format: "%.0f%%"
            args: [ 'x' ]  

# Scripts

script:
  - id: update_connection_status
    then:
      - delay: 10s # api.connected without some wait
      - if: 
          condition: 
              api.connected:
                  state_subscription_only: true
          then: 
            - lvgl.led.update:
                id: connection_dot
                color: 0x22c55e
          else:
            - lvgl.led.update:
                id: connection_dot
                color: 0xef4444
  - id: power_off_screen
    then: 
      - script.execute: fade_out_backlight
      - script.wait: fade_out_backlight
      - lvgl.pause:
          show_snow: true


### LVGL

lvgl:
  - id: main_lvgl
    on_idle:
      timeout: 120s
      then: 
        - script.execute: power_off_screen
    on_resume: 
      then: 
        - script.execute: fade_in_backlight

    style_definitions:
      - id: sensor_container
        height: 80
        bg_opa: cover
        border_width: 1
        radius: 8
        shadow_width: 2
        shadow_ofs_y: 2
        shadow_color: 0x000000
        shadow_opa: 40%
        pad_all: 8

    top_layer:
        widgets:
          - container:
              id: header
              width: 480
              height: 80
              align: TOP_MID
              bg_color: 0x1a1a1a
              bg_grad_color: 0x2d2d2d
              bg_grad_dir: HOR
              bg_opa: COVER
              border_width: 0
              border_color: 0x2d2d2d
              pad_all: 12
              widgets:
                - button:
                    id: power_btn
                    width: 20
                    height: 20
                    y: -5
                    bg_opa: TRANSP
                    border_side: NONE
                    outline_width: 0
                    shadow_width: 0
                    pad_all: 0
                    on_press: 
                      then: 
                        - script.execute: power_off_screen
                    
                    widgets:
                      - label:
                          text: "\U000F0425"  # Power icon
                          text_color: 0x6b7280
                          text_font: material_icons_20

                # Heure
                - label:
                    id: time_label
                    text: "--:--"
                    align: CENTER
                    y: -12
                    text_font: montserrat_48
                    text_color: 0xf3f4f6
                    text_align: CENTER
                
                # Date
                - label:
                    id: date_label
                    text: " "
                    align: CENTER
                    y: 20
                    text_font: montserrat_14
                    text_color: 0x6b7280
                    text_align: CENTER

                # Connection indicator dot (right)
                - led:
                    id: connection_dot
                    width: 8
                    height: 8
                    x: 450
                    brightness: 100%
                    color: 0xef4444

    page_wrap: true
    pages:
      - id: main_page
        # skip: true
        width: 100%
        bg_color: 0x0f0f0f
        bg_opa: cover
        pad_top: 90
        pad_bottom: 8
        pad_left: 8
        pad_right: 8
        layout:
          type: FLEX
          flex_flow: COLUMN
          flex_align_main: START
          flex_align_cross: CENTER
          pad_row: 8
          pad_column: 8
        widgets:
          - button:
              id: light_btn
              state:
                checked: false
              width: 100%
              height: 72
              bg_color: 0x1f2937  # Gray-800 (off state)
              border_width: 1
              border_color: 0x374151  # Gray-700
              radius: 8
              shadow_width: 2
              shadow_ofs_x: 0
              shadow_ofs_y: 2
              shadow_color: 0x000000
              shadow_opa: 40%
              pad_all: 12
              layout: 
                type: FLEX
                flex_flow: ROW
                flex_align_main: SPACE_BETWEEN
                flex_align_cross: CENTER
              checked:
                bg_color: 0xb45309
                border_color: 0xd97706
              on_click:
                then: 
                  - light.toggle:
                      id: ${light}
              widgets:
                # Left side: Icon + Label
                - container:
                    width: 160
                    layout: 
                      type: FLEX
                      flex_flow: ROW
                      flex_align_main: START
                      flex_align_cross: CENTER
                      pad_column: 8
                    widgets: 
                      - label:
                          id: light_icon
                          text: "\U000F0335"  # Lightbulb icon
                          text_color: "0xa1a5b0"  # Gray-600
                          text_font: material_icons_24
                          state:
                            checked: false
                          checked:
                            text_color: 0xfcd34d
                      # Text group
                      - container:
                          width: 120
                          layout: 
                            type: FLEX
                            flex_flow: COLUMN
                            flex_align_main: CENTER
                          widgets:
                            - label:
                                id: light_label
                                text: "Lumiere"
                                text_color: "0xf3f4f6"  # Gray-100
                                text_font: montserrat_16
                                text_align: LEFT
                            - label:
                                id: light_state_off
                                text: "Eteinte" 
                                text_color: "0x9ca3af"  # Gray-400
                                text_font: montserrat_12
                                text_align: LEFT
                            - label:
                                id: light_state_on
                                text: "Allumee"
                                hidden: true
                                text_color: "0x9ca3af"  # Gray-400
                                text_font: montserrat_12
                                text_align: LEFT
                # Right side: Status indicator text
                - label:
                    id: light_status_text_off
                    bg_color: "0x2d3748"  # Gray-700
                    border_width: 1
                    border_color: "0x4b5563"  # Gray-600
                    radius: 6
                    text: "Toucher pour allumer"  # Sans accents
                    text_color: "0x9ca3af"  # Gray-400
                    text_font: montserrat_12
                    text_align: CENTER
                    pad_right: 10
                    pad_left: 10
                    pad_top: 4
                    pad_bottom: 4
                - label:
                    id: light_status_text_on
                    hidden: true
                    bg_color: "0x2d3748"  # Gray-700
                    border_width: 1
                    border_color: "0x4b5563"  # Gray-600
                    radius: 6
                    text: "Toucher pour eteindre"  # Sans accents
                    text_color: "0x9ca3af"  # Gray-400
                    text_font: montserrat_12
                    text_align: CENTER
                    pad_right: 10
                    pad_left: 10
                    pad_top: 4
                    pad_bottom: 4
          # Grid sensor
          - container:
              id: sensors_grid
              width: 100%
              height: 80
              layout: 
                type: FLEX
                flex_flow: ROW
                flex_align_main: SPACE_BETWEEN
                flex_align_cross: CENTER
                pad_column: 8
              widgets: 
                # Temperature card
                - container: 
                    id: temp_card
                    styles: sensor_container
                    bg_color: 0x7c2d12 # Red-900
                    border_color: 0x92400e  # Orange-900
                    flex_grow: 1
                    layout: 
                      type: FLEX
                      flex_flow: ROW
                      flex_align_main: SPACE_BETWEEN
                      flex_align_cross: CENTER
                      flex_align_track: CENTER
                    widgets: 
                      - label:
                          text: "\U000F050F"
                          text_color: "0xfed7aa"  # Orange-200
                          text_font: material_icons_28
                      - label:
                          id: temp_value
                          text: "--°"
                          text_color: "0xfef3c7"  # Amber-100
                          text_font: montserrat_40
                          text_align: CENTER
                # Humidity card
                - container: 
                    id: humidity_card
                    styles: sensor_container
                    bg_color: 0x0c4a6e  # Blue-900
                    border_color: 0x164e63  # Cyan-900
                    flex_grow: 1
                    layout: 
                      type: FLEX
                      flex_flow: ROW
                      flex_align_main: SPACE_BETWEEN
                      flex_align_cross: CENTER
                      flex_align_track: CENTER
                    widgets: 
                      - label:
                          text: "\U000F058E"
                          text_color: 0xa5f3fc  # Cyan-300
                          text_font: material_icons_28
                      - label:
                          id: humidity_value
                          text: "--%"
                          text_color: 0xa5f3fc  # Cyan-300
                          text_font: montserrat_40
                          text_align: CENTER

font:
  - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/refs/heads/master/fonts/materialdesignicons-webfont.ttf"
    id: material_icons_20
    size: 20
    glyphs: [
      "\U000F06B5", # mdi-lightbulb
      "\U000F0425" # mdi:power
      
    ]
  - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/refs/heads/master/fonts/materialdesignicons-webfont.ttf"
    id: material_icons_24
    size: 24
    glyphs: [
      "\U000F0335"
    ]
  - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/refs/heads/master/fonts/materialdesignicons-webfont.ttf"
    id: material_icons_28
    size: 28
    glyphs: [
      "\U000F050F", # mdi:thermometer
      "\U000F058E" # mdi:water-percent
    ]

# Touchscreen resuming

touchscreen:
  - id: main_touchscreen
    on_release:
      then:
        - if:
            condition: lvgl.is_paused
            then:
              - lvgl.resume: